<<<<<<< HEAD
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
{
  "scripts": {
		"build": "tsc && vite build && echo '/* /index.html 200' | cat > dist/_redirects",
    },
}
>>>>>>> fd15938 (fix: Netlify 배포 리다이렉트 설정)
